name: Independent Content Preview

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Content Repository
        uses: actions/checkout@v4
        with:
          path: 'content'

